import { createClient } from '@supabase/supabase-js';
import { NextResponse } from 'next/server';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

// GET /api/support/tickets?email=user@example.com
export async function GET(request) {
  try {
    const { searchParams } = new URL(request.url);
    const email = searchParams.get('email');

    if (!email) {
      return NextResponse.json({ error: 'email is required' }, { status: 400 });
    }

    const { data: tickets, error } = await supabase
      .from('support_tickets')
      .select('*')
      .eq('user_email', email)
      .order('created_at', { ascending: false });

    if (error) throw error;

    return NextResponse.json({ success: true, tickets: tickets || [] });
  } catch (err) {
    console.error('GET /api/support/tickets error:', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

// POST /api/support/tickets
export async function POST(request) {
  try {
    const body = await request.json();
    const { user_email, user_name, user_id, subject, category, priority = 'normal', message } = body;

    if (!user_email || !subject || !category || !message) {
      return NextResponse.json(
        { error: 'user_email, subject, category, and message are required' },
        { status: 400 }
      );
    }

    // Create the ticket (ticket_number auto-generated by DB trigger)
    const { data: ticket, error: ticketError } = await supabase
      .from('support_tickets')
      .insert({
        ticket_number: '',
        user_id: user_id || null,
        user_email,
        user_name: user_name || null,
        subject,
        category,
        priority,
        status: 'open',
      })
      .select()
      .single();

    if (ticketError) throw ticketError;

    // Insert the first message
    const { error: msgError } = await supabase
      .from('support_ticket_messages')
      .insert({
        ticket_id: ticket.id,
        sender_type: 'user',
        sender_email: user_email,
        sender_name: user_name || null,
        message,
      });

    if (msgError) throw msgError;

    return NextResponse.json({ success: true, ticket }, { status: 201 });
  } catch (err) {
    console.error('POST /api/support/tickets error:', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
